name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest>=7.0.0 pytest-cov>=3.0.0 black>=22.0.0 flake8>=4.0.0 twine>=4.0.0 build>=0.7.0
        pip install -e .
    
    - name: Run tests
      run: |
        pytest tests/ -v